### ISSUE TITLE
[Suggestion] Removing login template (html) from salt-api ?

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-ui#12]
Hi,

I am wondering about implementing the "login routage" (and by that all routes) in salt-ui instead of salt-api. This technique could apply:

http://www.espeo.pl/2012/02/26/authentication-in-angularjs-application

The rest API doesn't really need a redirection to a "login.html" page and the tmpl directory could be removed for clarity sake.

There would be not much to be deleted on the cherrypy page, probably just https://github.com/saltstack/salt-api/blob/develop/saltapi/netapi/rest_cherrypy/__init__.py#L83-L93  and a couple of other related lines.

I can have a go and give you a pull request if you believe in the idea.

What do you think ?

Cheers

**Comment by whiteinge** [comment]
I agree with you completely. salt-api doesn't (currently) handle any responses in HTML aside from login and it would be a good move to pull that tmpl directory out entirely and into this project.

Regarding Angular:

We've gone back and forth on what the software stack for salt-ui should be (a few times) and I don't think Angular's dependency injection and module system are going to be flexible enough for our needs. Nothing against Angular! It's a really exciting project and full of good ideas.

I'm working to formulate the first pre-alpha salt-ui release right now -- hoping to have it ready by Monday. I would like to retain the exciting features of Angular (custom HTML tags, HTML as templates, two-way data binding, plain JavaScript models) through a handful of micro libraries. The WIP is in my fork. I am definitely open to feedback/criticism.

On a related note, thank you very much for the pull request fixing fixing those copy/paste errors! I apologize for not communicating intent on the current state of the project. We'll get this sorted out once we cut the first release. :-P

**Comment by whiteinge** [comment]
Moved in 1f03017.
