### ISSUE TITLE
Component: arguments

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#17]
Display in-line help & validation for required/optional aguments once a user has selected a command to run. This will be useful for the execution component as well as the SLS editor component.

Reqs saltstack/salt#2956.

**Comment by PierreR** [comment]
Any update on this one ? It makes the UI far less usable (many arg commands are not working)

**Comment by whiteinge** [comment]
Thanks for the reminder. The upstream ticket for this in Salt is probably a little ways off still so I think we need an interim fix so this is at least usable. I'll file a new ticket and schedule it for the next release.

**Comment by PierreR** [comment]
I believe we have an issue here that is salt-ui specific. With the API I can pass

```
  [
      {
          "client": "local",
          "tgt": "*",
          "fun": "cmd.run",
          "arg": [
              "ls -la",
              "cwd=/home/vagrant"
          ]
      }
  ]   
```

If I am not mistake there is currently no way to do this in the ui.
I have tried `'ls -la'  cwd=/home/vagrant`

Note that `'ls' cwd=/home/vagrant` works if you are careful enough to separate with just one space ;-)

**Comment by whiteinge** [comment]
This is issue #39. The fix is to add multiple "arg" inputs to the execution form and to bind those to the "arg" array in the view-model.

**Comment by PierreR** [comment]
So you believe there is no way to achieve this replacing the current arg "single space" separator with something else  ?

**Comment by whiteinge** [comment]
We could work around this by using some other delimiter. There are more open-ended commands (such as the `cmd.run` or `cmd.exec_code` commands) that would be difficult to get right. The cleanest solution is to use multiple <input> fields.

Fixing #39 shouldn't be much work. I'll bump that up on my priority list. This limitation needs to be fixed. :)

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
