### ISSUE TITLE
After editing the args in a command, empty args are resent in subsequent commands

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#21]

**Comment by PierreR** [comment]
This explains why if I remove "*" on the target box and leave it empty, then on pressing execute I can see that a bunch of /jobs/undefined hxr query are fired (something like 20 of them) ?

**Comment by whiteinge** [comment]
I think you're right about that. I started work on providing live-validation to execution commands last Thursday which should greatly help this sort of thing.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
