### ISSUE TITLE
Handle 403 (user is authenticated but is not authorized)

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-ui#31]
Salt API should send :
- 401 when the user is not authenticated
- 403 when the user is authenticated but is not allowed to perform an action

Then Salt-ui needs to ask for authentication if 401 and display a message if 403.

**Comment by whiteinge** [comment]
You're very right that this presents a usability problem for salt-ui. Currently Salt itself doesn't make a distinction between authenticated/authorized. From a security perspective this _may_ be the best behavior but not at the expense of a confusing UI. There is an open issue in Salt, issue saltstack/salt#3123, to only return functions/docs that the current user is authorized to use. I do like your idea of returning a 403 (it would simplify things for salt-ui) but I'm not sure yet how that fits into Salt's overall security policy.

**Comment by whiteinge** [comment]
Waiting on:

saltstack/salt-api#58
saltstack/salt-api#59

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
