### ISSUE TITLE
Dashboard: real-time stats

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#43]
Use output from the status execution module.

**Comment by aboe76** [comment]
For displaying realtime charts have a look at:
http://www.rgraph.net/examples/index.html

I think these will do nicely and are all free to use

**Comment by whiteinge** [comment]
That lib looks pretty nice. The licensing isn't great but also isn't bad. Thanks for the link.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
