### ISSUE TITLE
Dashboard: master configuration

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#44]

**Comment by aboe76** [comment]
@whiteinge maybe you can use some of these switches when you build a configuration page:
[switches](http://www.larentis.eu/switch/)

**Comment by whiteinge** [comment]
Thanks for the link. Those look very nice.

**Comment by whiteinge** [comment]
WIP design reference pushed to develop. Awaiting a better mechanism for not hard-coding the HTML-ification of the existing YAML source file. (Perhaps saltstack/salt#4352 or something similar.)

**Comment by aboe76** [comment]
It looks nice really like the extra information provided with each setting.
only thing I can see is missing, is the parsing of the extra config files in /etc/salt/master.d/
I have a habit to overwrite the defaults with files in /etc/salt/master.d/
so for example with external_auth, i will create a file external_auth_pam.conf.
in there I will set the params for external_auth

The reason for doing this is I can update the salt-package easily without the need to update
the config files when ever a new feature is added, this will be added in the default config file,
which I don't touch.

I hope I made myself clear.

**Comment by whiteinge** [comment]
That is good feedback. Any extra data structures are available in the output from the config wheel module however:

We need a way to display generic data structures in the form for user-specific config as well as some of the more complicated Salt config (external_auth, file_roots, etc). key/value pairs are obvious in an HTML form but anything more complicated...not so much.

Options discussed thus far:
- Display the YAML in a small text-editor style widget
- Come up with a HTML form builder that maps certain data structure types to certain HTML form fields. This is complicated by some Salt config options can accept different data structures for the same config value.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
