### ISSUE TITLE
Add tgt_type to execution component

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#46]

**Comment by PierreR** [comment]
Does this mean that currently only "local" works ?

I am trying a simple "runner" command from the ui which seems to looks fine in the debug browser console:

```
[{"client":"runner","tgt":"*","fun":"jobs.list_jobs","arg":[]}]
```

But it always return `is not available`

If you confirm there is something missing, I can have a look and try fixing it

**Comment by PierreR** [comment]
Trying to understand this, I see that a curl direct command works:

```
curl -sS localhost:8000/ -H "X-Auth-Token: eeb84466" -H 'Accept: application/x-yaml' -H 'Content-Type: application/json' --data @low.json
```

But a async doesn't:

```
curl -sS localhost:8000/minions -H "X-Auth-Token: eeb84466" -H 'Accept: application/x-yaml' -H 'Content-Type: application/json' --data @low.json

sudo salt-run jobs.print_job 20130429154355024252
```

It might make some sense but I don't really get it ... How are we supposed to interact with the API to run an async "runner" command ?

**Comment by whiteinge** [comment]
`tgt_type` is for minion targeting (glob, regex, compound, grains, list).

The problem you're running into with the "/minions" URL is that URL hard-codes "local_async" as the client so it is not trying to execute a runner module at all. There is not an asynchronous analogue for runners. Runners execute synchronously in Salt and in salt-api.

**Comment by whiteinge** [comment]
Also note the argument names that the runner client expects -- it is not the same as it is for the local client. The reason for that is the functions that the runner client executes are executed locally on the master whereas the local client instead collects enough information to pass to a minion so that the minion can execute that function remotely.

For example, look at the docs for the [print_job](http://docs.saltstack.com/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.print_job) runner and you'll see that it takes `job_id` as an argument. So the lowstate to execute that function would look like this:

``` bash
curl -sS localhost:8000 -d client='runner' -d fun='jobs.print_job' -d job_id='20130429135521683964'
```

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
