### ISSUE TITLE
Add setup.py installer

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-ui#48]
Installing as a Python package will allow:
- Distributing production builds (concat & minified) of the JS/CSS files and any production optimizations for the other static assets.
- Allow salt-api to programmatically detect salt-ui installation, location, and to verify on the version number.
- Give flexibility to override salt-ui assets by placing files in the normal /src/salt directory.

**Comment by aboe76** [comment]
@whiteinge because of salt-ui needs to be installed on a salt-master, could salt-ui not utilize

```
salt '$SALTMASTER' state.sls salt-ui to install salt-ui?
```

**Comment by whiteinge** [comment]
You're right, that would work. We're using setup.py for a few reasons that should be detailed in the ticket description...I'll add those now.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
