### ISSUE TITLE
multiple errors running salt-ui

### ISSUE THREAD

**Issue by aboe76** [vmware-archive/salt-ui#50]
running 
salt-git 
salt-api-git 
and salt-ui-git

Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:235
chromeHidden.Port.dispatchOnDisconnect miscellaneous_bindings:235
Uncaught TypeError: Cannot set property 'templateSettings' of undefined templates.js:20
(anonymous function) templates.js:20
context.execCb require.js:1597
Module.check require.js:845
(anonymous function) require.js:1083
(anonymous function) require.js:130
(anonymous function) require.js:1126
each require.js:58
Module.emit require.js:1125
Module.check require.js:899
Module.enable require.js:1113
Module.init require.js:758
callGetModule require.js:1140
context.completeLoad require.js:1511
context.onScriptLoad require.js:1618

GET http://localhost:8000/js/lib/asevented.js?bust=1364924008961 404 (Not Found) require.js:1836
req.load require.js:1836
context.load require.js:1586
Module.load require.js:804
Module.fetch require.js:794
Module.check require.js:824
Module.enable require.js:1113
context.enable require.js:1458
(anonymous function) require.js:1098
(anonymous function) require.js:130
each require.js:58
Module.enable require.js:1060
Module.init require.js:758
callGetModule require.js:1140
context.completeLoad require.js:1491
context.onScriptLoad require.js:1618
Uncaught Error: Script error

http://requirejs.org/docs/errors.html#scripterror require.js:160
makeError require.js:160
context.onScriptError

missing asevented.js in js/lib.
and missing config properties I think.

**Comment by whiteinge** [comment]
Thanks for the report. You happened to clone between adding that lib and pulling all third-party libs out of the repo. If you update now and install the third-party libs (see the README) it should be working.

**Comment by aboe76** [comment]
still got some errors:

GET http://localhost:8000/js/lib/less.js 404 (Not Found) localhost/:10
GET http://localhost:8000/js/lib/require.js 404 (Not Found) localhost/:10
Port error: Could not establish connection. Receiving end does not exist. miscellaneous_bindings:235

**Comment by aboe76** [comment]
ow I didn't read libs.txt, working now
