### ISSUE TITLE
erratic results  with salt 0.15.1 (simple test.ping or disk.usage)

### ISSUE THREAD

**Issue by PierreR** [vmware-archive/salt-ui#52]
I currently have two minions up. When I try a simple `test.ping` command  multiple times in a row, sometimes I get one minion back as a result, sometimes I get both of them.

This erratic behavior is rather constant and easy to reproduce.

When I try a more complicated command (e.g `disk.usage`) I only receive the reply back from a single minion.

I have run the same query with the salt-api and it seems to run without any glitches (with both `test.ping` or `disk.usage`):

```
curl -v http://myserver/minions  -H "Accept: application/x-yaml" -H "X-Auth-Token: 1fdsfs159kdksmc61220be" -d client=local -d tgt='*' -d fun='test.ping'
curl -v http://myserver/jobs/20130612161218231909
```

What's going on ? Of course the query sequence is faster but I can't believe it is actually possible to retrieve a partial result from a `jid`  ? Still I can see that the partial result is indeed retrieved in the chrome console and if I use the same `jid` with the salt-api  I do get the expected result (not the partial one) ...

I can hardly believe what I see. Could you confirm this bug ? Maybe it is related to the salt-master version and it has been fixed in 0.15.3. Though to me it is a bit too severe a flaw to be on the master side.

I am using salt 0.15.1 on the master from the CentOS EPEL stable repo, salt-api 0.8.1 and the latest salt-ui from github.

Thanks

**Comment by whiteinge** [comment]
It is possible to retrieve partial results when looking up a JID in both Salt and salt-api. Salt will return the result from all minions that have returned thus far. It sounds like salt-ui is grabbing the job after the faster minion has returned and before the slower minion has returned.

There are two things that should be addressed here:
1. salt-ui needs a refresh button to manually refresh a job return. (Also, once salt-ui can tap into Salt's event bus this can also be done automatically.)
2. salt-api needs a builtin mechanism for determining when a job is done. See also: saltstack/salt-api#92.

**Comment by whiteinge** [comment]
@PierreR thanks for bringing this up, btw! This has been a recurring puzzle and I think we've finally come up with a good solution for it (detailed in that salt-api ticket).

**Comment by PierreR** [comment]
For the record, I have just added a comment to the salt-api ticket. I really don't see why the salt master would not provide a way to know the status of a job through the `runners` API.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
