### ISSUE TITLE
Do you have a release date (ETA) for salt-ui 

### ISSUE THREAD

**Issue by JanickRoss** [vmware-archive/salt-ui#53]
I would like know if you have a release date for a usable version of salt-ui ?

Thanks

**Comment by whiteinge** [comment]
There has been some movement here not apparent in this project. For details, I will defer this question to @thatch45

**Comment by PierreR** [comment]
What do you mean by  "some movement here not apparent in this project" ? A change of direction ?

I have been thinking about this lately wondering about [retry](https://github.com/saltstack/salt-ui/blob/develop/js/utils/func.js#L350-L363) and a SSE possible alternative (or websocket). I have even wondered about [Pedestal](http://pedestal.io/) though using a non-python netapi does not seem easy.

**Comment by whiteinge** [comment]
I think you're spot-on about SSE. Polling via that retry function is definitely a hack. Listening in on Salt's event bus would be a great way for real-time notifications for when to update the display (e.g., listening for when a particular job ID finishes or updates) -- and SSE is the clear winner for enabling that. I just added a ticket to salt-api to get this added: saltstack/salt-api#95. Adding it to the UI could be done in just a few lines of code (ignoring the shim for IE).

Regarding this project, I'll say that we (finally) have a clear focus on where to drive the project and we also have manpower to make it happen. There should be an announcement on it very soon (probably in the couple of weeks range) to start getting the community more involved.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
