### ISSUE TITLE
curl does not follow redirects

### ISSUE THREAD

**Issue by hdonnay** [vmware-archive/salt-ui#54]
`Makefile` in `js/lib` should read like this:

```
# Download copies of all third-party libs and check hashes

all:
        -curl -LK libs.txt
        -md5sum --check --quiet md5sums.txt

clean:
        -rm *.js
```

**Comment by whiteinge** [comment]
Thanks for the report. It looks like the less.js URL has been changed.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
